---
step_name: preprocessing
step_factory_class: FrameworkProcessor
processor_init_config:
  env:
    OUTPUT_FILENAME: output.parquet
  estimator_cls_name: SKLearn
  framework_version: 1.2-1
  instance_count: 1
  instance_type: ml.m5.xlarge
processor_run_config:
  code: preprocess.py
  inputs:
    input_3: s3://smp-oo-example/examples/data/input_3
  outputs:
    output_1: s3://smp-oo-example/examples/data/output_1
  source_dir: worker_code/preprocess
